name: gd-godot-engine-snapcraft
license: GPL-3.0
summary: Godot Engine
description: |
  Godot Engine
base: core20
grade: stable
confinement: strict

adopt-info: gd-godot-engine-snapcraft

architectures:
  - build-on: amd64

apps:
  logisim-snapcraft:
    extensions: [gnome-3-38]
    command: godot
    plugs:
      - gsettings
      - opengl
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
  gd-godot-engine-snapcraft:
    plugin: nil
    source: https://github.com/godotengine/godot.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags `git rev-list --tags --max-count=1`)" -b latest
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    override-build: |
      scons -j$(nproc) platform=linuxbsd
    build-packages:
      - git
      - sed
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxinerama-dev
      - libgl1-mesa-dev
      - libglu-dev
      - libasound2-dev
      - libpulse-dev
      - libudev-dev
      - libxi-dev
      - libxrandr-dev
    stage-packages:
      - libgtk-3-0