name: gd-godot-engine-snapcraft
license: MIT
summary: Godot Engine
description: |
  Godot Engine
base: core22
grade: stable
confinement: strict

adopt-info: gd-godot-engine-snapcraft

architectures:
  - build-on: amd64
    build-for: amd64

apps:
  gd-godot-engine-snapcraft:
    extensions: [gnome]
    command: godot-engine/godot-engine
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - home
      - opengl
      - browser-support
      - gsettings
      - pulseaudio
      - audio-playback
      - joystick
      - removable-media
      - network
      - network-bind

parts:
  gd-godot-engine-snapcraft:
    plugin: nil
    source: https://github.com/godotengine/godot.git
    source-type: git
    override-pull: |
      craftctl default
      git checkout "$(git describe --tags `git rev-list --tags --max-count=1`)" -b latest
      craftctl set version="$(git describe --tags `git rev-list --tags --max-count=1`)"
    override-build: |
      # Python
      python3 -c "import sys; print(sys.version)"
      python3 -m pip install scons
      
      # Version
      python3 --version
      pip3 --version
      scons --version
      dotnet --info

      # Scons
      scons platform=linuxbsd target=editor tests=false verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes module_mono_enabled=yes

      # Generate C# glue
      ./bin/godot.* --headless --generate-mono-glue ./modules/mono/glue || true

      # Build .NET Solution
      ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd
      
      # Generate package
      strip bin/godot.*
      chmod +x bin/godot.*
      cd bin
      mv godot.* godot-engine
      mkdir $CRAFT_PART_INSTALL/godot-engine
      mv * $CRAFT_PART_INSTALL/godot-engine
    build-packages:
      - git
      - sed
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxinerama-dev
      - libgl1-mesa-dev
      - libglu-dev
      - libasound2-dev
      - libpulse-dev
      - libudev-dev
      - libxi-dev
      - libxrandr-dev
      - python3
      - python3-pip
      - dotnet6
    stage-packages:
      - dotnet6
      - libspeechd2
      - libpulse0
      - libasound2
      - libnss3
      - libxss1
      - libxtst6
      - libnspr4
      - libimlib2
      - libx11-6
      - libxcursor1
      - libfreetype6
      - libgl1
      - libegl1-mesa
      - libglvnd0
      - libglu1
      - libglu1-mesa
      - freeglut3
      - mesa-vdpau-drivers
      - mesa-utils
      - mesa-utils-extra
      - libvulkan1
      - mesa-vulkan-drivers
      - vulkan-tools
