name: gd-godot-engine-snapcraft
license: GPL-3.0
summary: Godot Engine
description: |
  Godot Engine
base: core20
grade: stable
confinement: strict

adopt-info: gd-godot-engine-snapcraft

architectures:
  - build-on: amd64

apps:
  logisim-snapcraft:
    extensions: [gnome-3-38]
    command: godot
    plugs:
      - gsettings
      - opengl
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
  gd-godot-engine-snapcraft:
    plugin: nil
    source: https://github.com/godotengine/godot.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags `git rev-list --tags --max-count=1`)" -b latest
      snapcraftctl set-version "$(git describe --tags | sed 's/v//' | sed "s/-g/%/"  | cut -d "%" -f1)"
    override-build: |
      scons -j$(nproc) platform=linuxbsd
      tree
    build-packages:
      - tree
      - git
      - sed
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxinerama-dev
      - libgl1-mesa-dev
      - libglu-dev
      - libasound2-dev
      - libpulse-dev
      - libudev-dev
      - libxi-dev
      - libxrandr-dev
    stage-packages:
      - libgtk-3-0
    
  gd-godot-engine-mono-snapcraft:
    plugin: nil
    source: https://github.com/godotengine/godot.git
    source-type: git
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags `git rev-list --tags --max-count=1`)" -b latest
    override-build: |
      scons p=linuxbsd target=release_debug tools=true tests=false -j$(nproc) module_mono_enabled=yes mono_static=yes mono_glue=no
      tree bin/
      ./bin/godot.x11.opt.tools.64.mono --generate-mono-glue modules/mono/glue || true
      scons p=linuxbsd target=release_debug tools=true tests=false -j$(nproc) module_mono_enabled=yes mono_static=yes mono_glue=no mono_glue=yes
      tree bin/
    build-snaps:
      - dotnet-sdk/latest/stable
    build-packages:
      - tree
      - git
      - sed
      - build-essential
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libxinerama-dev
      - libgl1-mesa-dev
      - libglu-dev
      - libasound2-dev
      - libpulse-dev
      - libdbus-1-dev
      - libudev-dev
      - libxi-dev
      - libxrandr-dev
      - yasm
      - xvfb
      - wget
      - unzip
      - llvm
      - libspeechd-dev
      - speech-dispatcher
      - mono-complete
    stage-packages:
      - libgtk-3-0

package-repositories:
  - type: apt
    components: [main]
    suites: [stable-bionic]
    key-id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    key-server: hkp://keyserver.ubuntu.com:80
    url: https://download.mono-project.com/repo/ubuntu
